[project]
name = "riot-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
packages = ["src"]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "pydantic>=2.11.7",
]
